config/routes.rb
Notepad::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :my_notes do
    collection do
      get :deleted
      get :search
    end
    member do
      get :content
      get :html_content
      post :delete
      post :undelete
    end
  end

  resources :groups

  resources :images

  resource :evernote, controller: :evernote do
    member do
      get :auth_callback
    end

    resources :notebooks, controller: :evernote_notebooks
  end

  resources :settings

  resource :dashboard, controller: :dashboard, only: :show

  root :to => 'home#index'

end

app/controllers/my_notes_controller.rb
class MyNotesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @notes = current_user.latest_notes.select(:id, :title, :created_at, :updated_at).page(params[:page])
    respond_to do |format|
      format.html
      format.json do
        render json:@notes.as_json(:methods => :title)
      end
    end
  end

  def search
    if params[:q]
      q = params[:q]
      user_id = current_user.id
      @notes = Note.search page: params[:page] || 1 do
        query {string q}
        filter :terms, user_id: [user_id]
      end
      respond_to do |format|
        format.html
        format.json{ render json: @notes }
      end
    end
  end

  def deleted
    @notes = current_user.deleted_notes.select(:id, :title, :created_at, :updated_at).page(params[:page])
    respond_to do |format|
      format.html
      format.json do
        render json:@notes.as_json(:methods => :title)
      end
    end
  end

  def new
    create
  end

  def create
    @note = Note.create!(user: current_user)
    redirect_to action: :edit, id:@note
  end

  def show
    @note = current_user.notes.find(params[:id])
    respond_to do |format|
      format.html do
        redirect_to :edit
      end
      format.json do
        render json: @note
      end
    end
  end

  def content
    @note = current_user.notes.find(params[:id])
    render layout: false
  end

  def html_content
    @note = current_user.notes.find(params[:id])
    render layout: false
  end

  def edit
    @note = current_user.notes.find(params[:id])
    respond_to do |format|
      format.html do
        render layout: 'note'
      end
    end
  end

  def update
    @note = current_user.notes.find(params[:id])
    respond_to do |format|
      format.json do
        if @note.update_attributes(content: params[:content], html_content: params[:html_content])
          render json:@note
        else
          render json:@note, :status => :unprocessable_entity
        end
      end
    end
  end

  def delete
    @note = current_user.notes.find(params[:id])
    if @note.move_to_trash
      head :ok
    else
      head :unprocessable_entity
    end
  end

  def undelete
    @note = current_user.notes.find(params[:id])
    if @note.move_to_inbox
      head :ok
    else
      head :unprocessable_entity
    end
  end

  def destroy
    @note = current_user.notes.find(params[:id])
    if @note
      @note.destroy
    end
    head :ok
  end
end

app/views/my_notes/_context_navbar.html.slim
-if params[:action] == 'index'
  =render 'index_menu'
-if params[:action] == 'edit'
  =render 'editor_menu'

app/views/my_notes/_editor_menu.html.slim
ul.nav.navbar-nav.note-editor-menu
  li.dropdown
    a.dropdown-toggle href="#" data-toggle="dropdown"
      i.icon-columns
      b.caret
    ul.dropdown-menu
      li
        a.toggle-sidebar href="#"
          | Headings
          i.icon-ok
      li
        a.toggle-preview href="#"
          | Preview
          i.icon-ok
  /li
  /  a.toggle-image-panel href="#"
  /    i.icon-camera

app/views/my_notes/_image_panel.html.slim
#image-panel.image-panel
  input#image_file type="file" name="file[]" data-url="/images" multiple=true

app/views/my_notes/_index_menu.html.slim
=form_tag search_my_notes_path, class: 'navbar-form navbar-left note-search', role: 'search', method: :get, remote: true do
  .form-group
    =search_field_tag :q, params[:q], class: 'form-control', placeholder: 'Search'
  =button_tag class: 'btn btn-default' do
    i.icon-search

app/views/my_notes/_navigation.html.slim
ul#navigation
  li = link_to 'Home', root_path
  li = link_to 'Notes', my_notes_path
  -if @note
    li = link_to @note.title, edit_my_note_path(@note)

app/views/my_notes/_templates.html.erb
<div id="templates">
  <script type="text/template" class="note-list-item">
    <div class="title">{{title}}</div>
    <div class="created_at">
      <span>{{updated_at}}</span>
      <ul class="note-index-actions">
        <li class="edit">
          <i class="icon-edit"></i>
        </li>
        <li class="delete">
          <i class="icon-trash"></i>
        </li>
      </ul>
    </div>
  </script>

  <script type="text/template" class="note-index-actions-template">
    <ul class="note-index-actions">
      <li class="edit">
        <i class="icon-edit"></i>
      </li>
      <li class="delete">
        <i class="icon-trash"></i>
      </li>
    </ul>
  </script>

  <script type="text/template" class="note-list-item-template">
    <div>
      <span>{{title}}</span>
    </div>
    <div>
      <span class="created_at">{{created_at}}</span>
    </div>
  </script>

  <script type="text/template" class="note-info">
    <span class="key">Created: </span>
    <span class="value">{{created_at}}</span>
    <span class="key">Updated: </span>
    <span class="value">{{updated_at}}</span>
  </script>
</div>

app/views/my_notes/_templates_for_deleted.html.erb
<div id="templates">
  <script type="text/template" class="note-list-item">
    <div class="title">{{title}}</div>
    <div class="created_at">
      <span>{{updated_at}}</span>
      <ul class="note-index-actions">
        <li class="undelete">
          <i class="icon-list"></i>
        </li>
      </ul>
    </div>
  </script>

  <script type="text/template" class="note-index-actions-template">
    <ul class="note-index-actions">
      <li class="undelete">
        <i class="icon-list"></i>
      </li>
    </ul>
  </script>

  <script type="text/template" class="note-list-item-template">
    <div>
      <span>{{title}}</span>
    </div>
    <div>
      <span class="created_at">{{created_at}}</span>
    </div>
  </script>

  <script type="text/template" class="note-info">
    <span class="key">Created: </span>
    <span class="value">{{created_at}}</span>
    <span class="key">Updated: </span>
    <span class="value">{{updated_at}}</span>
  </script>
</div>

app/views/my_notes/content.html.haml
.note-content
  =simple_format @note.content

app/views/my_notes/deleted.html.slim
.note-list-page.deleted-note-list-page
  .note-list-pane
    ul.note-list
    .more
      span.btn.more More
  .content-pane
    .note-info
    .note-preview-pane
      .note-preview
        article.note.note-html

=render 'templates_for_deleted'

app/views/my_notes/edit.html.slim
=render 'navigation'

.note data-id="#{@note.id}"
  .sidebar
    .index
    .handle
  .editor-container
    .editor
      textarea name="note[content]" id="note_content" cols="30" rows="10" tabindex="1"
      .footer
    .right-sidebar
      .handle
      .preview-pane
        .preview
    .note-state
    input.image-uploader type="file" name="file[]" data-url="/images" multiple=true
/#debug
/  .last-keyup
/  .time-since-last-change

/=render 'image_panel'

app/views/my_notes/html_content.slim
article.note.note-html
  -if @note.html_content.present?
    = raw @note.html_content
  -else
    = simple_format @note.content

app/views/my_notes/index.html.slim
=render 'navigation'

.note-list-page
  .note-list-pane
    ul.note-list
    .more
      span.btn.more More
  .content-pane
    .note-info
    .note-preview-pane
      .note-preview
        article.note.note-html

=render 'templates'

app/views/my_notes/search.html.slim
=form_tag nil, method: :get, class: 'search-form' do
  =search_field_tag :q, params[:q]
  =button_tag t('common.search')

-if @notes.present?
  ul.note-list
    -@notes.each do |note|
      li=note.title

app/views/my_notes/show.html.haml
.note{"data-id" => @note.id}
  .sidebar
    .index
    .handle
  .editor-container
    .editor
      %textarea(name="note[content]" id="note_content" cols="30" rows="10" tabindex="1" )
      .footer
    .right-sidebar
      .handle
      .preview-pane
        .preview

#debug
  .last-keyup
  .time-since-last-change