config/routes.rb
Notepad::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :my_notes do
    collection do
      get :deleted
      get :search
    end
    member do
      get :content
      get :html_content
      post :delete
      post :undelete
    end
  end

  resources :groups

  resources :images

  resource :evernote, controller: :evernote do
    member do
      get :auth_callback
    end

    resources :notebooks, controller: :evernote_notebooks
  end

  resources :settings

  resource :dashboard, controller: :dashboard, only: :show

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper

  def note_page?
    params[:controller] == "my_notes" && params[:action] == "show"
  end

  def title(s)
    content_for :title, s
  end

  def first_page?
    params[:page].blank? || params[:page].to_i <= 1
  end
end

app/views/application/_navigation_bar.html.slim
.navbar.navbar-default.navbar-fixed-top
  a.navbar-brand href="#{root_path}" Notepad
  ul.nav.navbar-nav
    /%li=link_to "My Notes", my_notes_path
    -if user_signed_in?
      li
        a href="#{my_notes_path}"
          i.icon-list
      li
        =link_to my_notes_path, method: :post do
          i.icon-file-text-alt
          | +
      li.dropdown
        a.dropdown-toggle href="#" data-toggle="dropdown"
          i.icon-inbox
          b.caret
        ul.dropdown-menu.pull-right
          li
            =link_to deleted_my_notes_path do
              i.icon-trash
              =" #{t('common.trash')}"
  =render 'context_navbar'
  ul.nav.navbar-nav.navbar-right
    -if user_signed_in?
      li.dropdown
        a.dropdown-toggle href="#" data-toggle="dropdown"
          span.user-icon=image_tag current_user.image if current_user.image.present?
          =current_user.name
          b.caret
        ul.dropdown-menu
          li
            =link_to settings_path do
              i.icon-gear
              |  Settings
          li
            =link_to destroy_user_session_path, :method => :delete do
              span.glyphicon.glyphicon-log-out
              =" #{t('session.sign_out')}"
    -else
      li=link_to 'Sign in with Twitter', user_omniauth_authorize_path(:twitter)